### ISSUE TITLE
clang-format is not a no-op on freshly cloned repository on F38

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#482]
``` diff
$ ./clang-format 
$ git diff
diff --git a/libdnf/repo/repo_downloader.cpp b/libdnf/repo/repo_downloader.cpp
index 69e5bf6a..8980b24d 100644
--- a/libdnf/repo/repo_downloader.cpp
+++ b/libdnf/repo/repo_downloader.cpp
@@ -533,7 +533,7 @@ void RepoDownloader::apply_http_headers(LibrepoHandle & handle) {
     std::unique_ptr<char * [], std::function<void(char **)>> lr_headers {
         nullptr, [](char ** ptr) {
             for (auto item = ptr; *item != nullptr; ++item) {
-                delete[] * item;
+                delete[] *item;
             }
             delete[] ptr;
         }
diff --git a/libdnf/utils/on_scope_exit.hpp b/libdnf/utils/on_scope_exit.hpp
index 4b6adaa1..46625094 100644
--- a/libdnf/utils/on_scope_exit.hpp
+++ b/libdnf/utils/on_scope_exit.hpp
@@ -28,8 +28,8 @@ namespace libdnf::utils {
 /// intended to call its exit function when a scope is exited.
 template <typename TExitFunction>
     requires requires(TExitFunction f) {
-                 { f() } noexcept;
-             }
+        { f() } noexcept;
+    }
 class OnScopeExit {
 public:
     OnScopeExit(TExitFunction && function) noexcept : exit_function{std::move(function)} {}
diff --git a/test/shared/private_accessor.hpp b/test/shared/private_accessor.hpp
index 13bfea54..08411a35 100644
--- a/test/shared/private_accessor.hpp
+++ b/test/shared/private_accessor.hpp
@@ -23,10 +23,12 @@ along with libdnf.  If not, see <https://www.gnu.org/licenses/>.
 
 
 // A getter generating structure
-#define create_private_getter_template                         \
-    template <typename AccessTag, typename T, T value>         \
-    struct PrivateGetter {                                     \
-        friend constexpr auto get(AccessTag) { return value; } \
+#define create_private_getter_template                 \
+    template <typename AccessTag, typename T, T value> \
+    struct PrivateGetter {                             \
+        friend constexpr auto get(AccessTag) {         \
+            return value;                              \
+        }                                              \
     }
 
 // Helper macro with automatic member type deduction
```

**Comment by jan-kolarik** [comment]
It seems like it depends on `clang-format` version or perhaps also some other environmental settings...

If I run it on my host computer running Fedora 37 and clang-format version 15.0.7, the output is clear.
If I run it on my container running Fedora 36 and clang-format version 14.0.5, I receive couple of changes, some of them are even different from the output provided here...

**Comment by kontura** [comment]
We have the version of `clang-format` that runs in upstream hard-coded in https://github.com/rpm-software-management/dnf5/blob/main/.pre-commit-config.yaml#L15

We could possibly remove the version to always have the newest?
Or perhaps it would be better to track newest active fedora (38)? 
I have updated my PR to match the f38 version for now.

**Comment by jan-kolarik** [comment]
I wasn't digging into this deeply, but it seems like two problems there. One is the using of `clang-format` in default mode which has apparently different configuration for 14/15/16 versions when no config file or arguments are given. The second problem is that in the dnf5 repo root we have the `.clang-format` configuration which is applied only when running it locally (is it right?) - f.e. this:

```
# Force middle pointer alignment.
#
# Examples:
# char * str;
# const std::string & str;
#
DerivePointerAlignment: false
PointerAlignment: Middle
```

Which does not match the proposed PR ...

**Comment by kontura** [comment]
I think the config `.clang-format` is always applied locally and upstream.
I believe the change in PR is not a pointer alignment but a de-reference.

**Comment by jan-kolarik** [comment]
OMG, you're right, I missed the context of around. Sorry about that.

**Comment by jan-kolarik** [comment]
Anyway, I still don't see the proposed PR as the final resolution. Because then users using F36/F37 or different `clang-format` versions could not rely on checking the format locally as it gives different results. Maybe we could add some explicit rules, so the formatting would behave the same across the versions?

**Comment by jan-kolarik** [comment]
Yep, but these would be hopefully just occasional exceptions.

It seems like the biggest difference is when using the `clang-format` 14 from Fedora 36 where the current configuration outputs quite a lot of changes:

```
diff --git a/include/libdnf/repo/repo_query.hpp b/include/libdnf/repo/repo_query.hpp
index cffb1823..95356f27 100644
--- a/include/libdnf/repo/repo_query.hpp
+++ b/include/libdnf/repo/repo_query.hpp
@@ -58,7 +58,9 @@ public:
 
     /// @return Weak pointer to the Base object.
     /// @since 5.0
-    libdnf::BaseWeakPtr get_base() { return base; }
+    libdnf::BaseWeakPtr get_base() {
+        return base;
+    }
 
     /// Filter repos by their `enabled` state.
     ///
diff --git a/libdnf/utils/on_scope_exit.hpp b/libdnf/utils/on_scope_exit.hpp
index 4b6adaa1..6c736315 100644
--- a/libdnf/utils/on_scope_exit.hpp
+++ b/libdnf/utils/on_scope_exit.hpp
@@ -27,9 +27,10 @@ namespace libdnf::utils {
 /// The class template OnScopeExit is a general-purpose scope guard
 /// intended to call its exit function when a scope is exited.
 template <typename TExitFunction>
-    requires requires(TExitFunction f) {
-                 { f() } noexcept;
-             }
+requires requires(TExitFunction f) {
+    { f() }
+    noexcept;
+}
 class OnScopeExit {
 public:
     OnScopeExit(TExitFunction && function) noexcept : exit_function{std::move(function)} {}
diff --git a/libdnf/utils/sqlite3/sqlite3.hpp b/libdnf/utils/sqlite3/sqlite3.hpp
index 4f147cf6..6b4a2979 100644
--- a/libdnf/utils/sqlite3/sqlite3.hpp
+++ b/libdnf/utils/sqlite3/sqlite3.hpp
@@ -219,20 +219,30 @@ public:
         /// Reset prepared query to its initial state, ready to be re-executed.
         /// All the bound values remain untouched - retain their values.
         /// Use clearBindings if you need to reset them as well.
-        void reset() { sqlite3_reset(stmt); }
+        void reset() {
+            sqlite3_reset(stmt);
+        }
 
-        void clear_bindings() { sqlite3_clear_bindings(stmt); }
+        void clear_bindings() {
+            sqlite3_clear_bindings(stmt);
+        }
 
         template <typename T>
         T get(int idx) {
             return get(idx, Identity<T>{});
         }
 
-        int64_t last_insert_rowid() { return db.last_insert_rowid(); }
+        int64_t last_insert_rowid() {
+            return db.last_insert_rowid();
+        }
 
-        SQLite3 & get_db() const { return db; }
+        SQLite3 & get_db() const {
+            return db;
+        }
 
-        ~Statement() { sqlite3_finalize(stmt); };
+        ~Statement() {
+            sqlite3_finalize(stmt);
+        };
 
     protected:
         template <typename T>
@@ -246,17 +256,25 @@ public:
             static_assert(sizeof(TL) == 0, "Not implemented");
         }*/
 
-        int get(int idx, Identity<int> /*unused*/) { return sqlite3_column_int(stmt, idx); }
+        int get(int idx, Identity<int> /*unused*/) {
+            return sqlite3_column_int(stmt, idx);
+        }
 
         uint32_t get(int idx, Identity<uint32_t> /*unused*/) {
             return static_cast<uint32_t>(sqlite3_column_int64(stmt, idx));
         }
 
-        int64_t get(int idx, Identity<int64_t> /*unused*/) { return sqlite3_column_int64(stmt, idx); }
+        int64_t get(int idx, Identity<int64_t> /*unused*/) {
+            return sqlite3_column_int64(stmt, idx);
+        }
 
-        double get(int idx, Identity<double> /*unused*/) { return sqlite3_column_double(stmt, idx); }
+        double get(int idx, Identity<double> /*unused*/) {
+            return sqlite3_column_double(stmt, idx);
+        }
 
-        bool get(int idx, Identity<bool> /*unused*/) { return sqlite3_column_int(stmt, idx) != 0; }
+        bool get(int idx, Identity<bool> /*unused*/) {
+            return sqlite3_column_int(stmt, idx) != 0;
+        }
 
         const char * get(int idx, Identity<const char *> /*unused*/) {
             return reinterpret_cast<const char *>(sqlite3_column_text(stmt, idx));
@@ -323,15 +341,23 @@ public:
     SQLite3(const SQLite3 &) = delete;
     SQLite3 & operator=(const SQLite3 &) = delete;
 
-    explicit SQLite3(const std::string & db_path) : path{db_path}, db{nullptr} { open(); }
+    explicit SQLite3(const std::string & db_path) : path{db_path}, db{nullptr} {
+        open();
+    }
 
-    ~SQLite3() { close(); }
+    ~SQLite3() {
+        close();
+    }
 
-    const std::string & get_path() const { return path; }
+    const std::string & get_path() const {
+        return path;
+    }
 
     void open();
     void close();
-    bool is_open() { return db != nullptr; };
+    bool is_open() {
+        return db != nullptr;
+    };
 
     void exec(const char * sql) {
         auto result = sqlite3_exec(db, sql, nullptr, nullptr, nullptr);
@@ -340,11 +366,17 @@ public:
         }
     }
 
-    int changes() { return sqlite3_changes(db); }
+    int changes() {
+        return sqlite3_changes(db);
+    }
 
-    int64_t last_insert_rowid() { return sqlite3_last_insert_rowid(db); }
+    int64_t last_insert_rowid() {
+        return sqlite3_last_insert_rowid(db);
+    }
 
-    std::string get_error() const { return sqlite3_errmsg(db); }
+    std::string get_error() const {
+        return sqlite3_errmsg(db);
+    }
 
     void backup(const std::string & output_file);
     void restore(const std::string & input_file);
```
While with the Fedora 37, `clang-format` version 15, the output is empty.

Maybe we could just try the best effort to sync and prepare the config for at least the Fedora 37 and Fedora 38. As these are the recent stable versions probably used by most of the developers. Or do you think we should just focus on the latest one?

**Comment by kontura** [comment]
> Maybe we could just try the best effort to sync and prepare the config for at least the Fedora 37 and Fedora 38.

I would like that but I am out of ideas how to improve the current situation.
I would probably drop the `RequiresExpressionIndentation` config so that it works on <38 but I don't know how to bring the results closer.
