### ISSUE TITLE
repoquery --unsatisfied

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#910]
I am not sure about importance of the option

**Comment by tasty0tomato** [comment]
I upgrade my system to 41. And dnf does not have this option.

**Comment by ppisar** [comment]
I think the option is not important for DNF because DNF does not allow installing a package with broken dependencies.

**Comment by jwadodson** [comment]
What an interesting approach to what I found a useful option!
Why was it suddenly not supported?

(On a game machine running FC40) I used to get,

 Problem: problem with installed package cncnet-1.0-2.noarch
  - nothing provides wine(x86-32) needed by cncnet-1.0-2.noarch from @System

from a "dnf repoquery --unsatisfied"

which was a reminder to me to some time work out why this was happening & report it.

I assume now in FC41 the anomaly that was a "need/dependency" on wine(x86-32) when it
was a 64 bit machine was or has been fixed?

**Comment by jwadodson** [comment]
Note that FC41 has only just been the preferred upgrade at,

https://docs.fedoraproject.org/en-US/quick-docs/upgrading-fedora-offline/

in the last few weeks.

**Comment by jwadodson** [comment]
How many other such options were removed?
dnf repoquery --duplicated
at least as well?

**Comment by kontura** [comment]
> How many other such options were removed? dnf repoquery --duplicated at least as well?

The option `--duplicates` (not `--duplicated`) is implemented and should be working.

You can check overview of the still missing option here: https://github.com/rpm-software-management/dnf5/issues/122
It should be: `--unsatisfied`, `--tree` and `--deplist`.

**Comment by jwadodson** [comment]
OK, thanks, but...
This all happened to me during the FC40 -> FC 41 upgrade...

        dnf-automatic seems to have been removed.

        many options that once worked now don't...

Not great to find these things out the hard way.

The comment above,

ppisar: I think the option is not important for DNF because DNF does not allow installing a package with broken dependencies.

Is all well & good, now, but I've often found such anomalies when trying to bring an old inherited machine back to a
manageable state after it's been neglected by someone.
A total reinstall tends to be a lot of work , but if the tools that were in the old dnf remain then it's a little
easier to understand what's been going on & correct it.

Is there a reason the logs are now in /var/log/dnf5.log & will they one day revert to /var/log/dnf.log?
or worse dnf6.log?

I have... after the FC40 -> FC41 upgrade, should it be different?
(Why did dnf-automatic get removed in the dnf5 conversion?)

# dnf list dnf*
Updating and loading repositories:
Repositories loaded.
Installed packages
dnf-data.noarch              4.21.1-2.fc41  updates
dnf-plugins-core.noarch      4.9.0-1.fc41   fedora
dnf-repo.x86_64              0.6.1-5.fc41   fedora
dnf-utils.noarch             4.9.0-1.fc41   fedora
dnf5.x86_64                  5.2.7.0-1.fc41 updates
dnf5-plugin-automatic.x86_64 5.2.7.0-1.fc41 updates
dnf5-plugins.x86_64          5.2.7.0-1.fc41 updates

Available packages
dnf.noarch                   4.21.1-1.fc41  fedora
dnf-automatic.noarch         4.21.1-1.fc41  fedora
dnf-plugin-diff.noarch       1.1-21.fc41    fedora
dnf-plugin-ovl.noarch        0.0.3-16.fc41  fedora
dnf5.i686                    5.2.7.0-1.fc41 updates
dnf5-devel.i686              5.2.7.0-1.fc41 updates
dnf5-devel.x86_64            5.2.7.0-1.fc41 updates
dnf5daemon-client.x86_64     5.2.7.0-1.fc41 updates
dnf5daemon-server.x86_64     5.2.7.0-1.fc41 updates
dnfdaemon.noarch             0.3.22-3.fc41  fedora
dnfdaemon-selinux.noarch     0.3.22-3.fc41  fedora
dnfdragora.noarch            2.1.5-7.fc41   fedora
dnfdragora-updater.noarch    2.1.5-7.fc41   fedora

**Comment by Arcitec** [comment]
I always use --unsatisfied to check for broken packages after OS upgrades. But I can't remember if it ever showed me anything. Seeing that another user above saw errors though, makes me think the option is still useful!

Scans all packages and ensures all their dependencies are still installed. Right? That's pretty useful!

**Comment by kontura** [comment]
> (Why did dnf-automatic get removed in the dnf5 conversion?)

It didn't, as you can see in your output, there is `dnf5-plugin-automatic.x86_64 5.2.7.0-1.fc41`.

However, there indeed are changes. You can checkout `automatic` section in https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html.

**Comment by jwadodson** [comment]
In my case, dnf-automatic was installed, (FC40) it was removed in the transition to FC41.

As examples of "something wrong", (as above) I like to check for broken packages after OS upgrades...

dnf -q list extras

gives nothing,

package-cleanup --quiet --orphans
gives... a mass of stuff from FC40

Which is exactly what I used to use --unsatisfied for!
To find & deal with such things.

**Comment by jwadodson** [comment]
Ah!!! package-cleanup (dnf-utils) still seems to do some of what I need...

When will it be clobbered? (deprecated?)

**Comment by tuxmaster5000** [comment]
I use it after update to check that packages are in an clean state, because third-party software sometimes install there packages via rpm instant of dnf.

**Comment by m-blaha** [comment]
I propose closing this issue and not implementing `dnf5 repoquery --unsatisfied` for the following reasons:

1. it does not fit the `repoquery` command, which is designed to emit package lists. Its various options only limit the list of packages it prints. The `--unsatisfied` option would be an exception: instead of producing a package list, it would print solver problems.
2. we already have a replacement: `dnf5 check --dependencies`. In fact, this command existed even in the dnf4 era. It iterates over the RPM database and uses librpm’s own check capabilities to report issues.
3. the output of `dnf check` is arguably easier for users to understand. It prints the root cause directly and nothing else. In contrast, `repoquery --unsatisfied` prints not only the primary problems but also transitively broken packages. While this may be useful, I would still propose adding an option such as `--recursive` to the `check` command to display those transitively broken packages. On top of that, the `dnf check` returns exit code 1 in case it finds errors, making it more suitable for usage in scripts.

Here is an example of the output produced by the discussed commands in the most common case, where a dependency of an installed package has been removed:

```
[root@7bd5898f58f4 /]# dnf install zypper -y && rpm -e zypp-common --nodeps

[root@7bd5898f58f4 /]# dnf4 repoquery --unsatisfied
Last metadata expiration check: 0:01:09 ago on Wed Sep  2 07:30:58 2026.

 Problem 1: problem with installed package libzypp-17.38.1-1.fc43.x86_64
  - nothing provides zypp-common = 17.38.1-1.fc43 needed by libzypp-17.38.1-1.fc43.x86_64 from @System
 Problem 2: problem with installed package zypp-plugins-17.38.1-1.fc43.noarch
  - nothing provides zypp-common = 17.38.1-1.fc43 needed by zypp-plugins-17.38.1-1.fc43.noarch from @System
 Problem 3: package zypper-1.14.94-1.fc43.x86_64 from @System requires libzypp.so.1735()(64bit), but none of the providers can be installed
  - package zypper-1.14.94-1.fc43.x86_64 from @System requires libzypp.so.1735(ZYPP_plain)(64bit), but none of the providers can be installed
  - package zypper-1.14.94-1.fc43.x86_64 from @System requires libzypp(x86-64) >= 17.37.12, but none of the providers can be installed
  - problem with installed package zypper-1.14.94-1.fc43.x86_64
  - nothing provides zypp-common = 17.38.1-1.fc43 needed by libzypp-17.38.1-1.fc43.x86_64 from @System
 Problem 4: package zypp-tools-17.38.1-1.fc43.x86_64 from @System requires libzypp.so.1735()(64bit), but none of the providers can be installed
  - package zypp-tools-17.38.1-1.fc43.x86_64 from @System requires libzypp.so.1735(ZYPP_plain)(64bit), but none of the providers can be installed
  - package zypp-tools-17.38.1-1.fc43.x86_64 from @System requires libzypp(x86-64) = 17.38.1-1.fc43, but none of the providers can be installed
  - problem with installed package zypp-tools-17.38.1-1.fc43.x86_64
  - nothing provides zypp-common = 17.38.1-1.fc43 needed by libzypp-17.38.1-1.fc43.x86_64 from @System
 Problem 5: package zypper-log-1.14.94-1.fc43.noarch from @System requires zypper = 1.14.94-1.fc43, but none of the providers can be installed
  - package zypper-1.14.94-1.fc43.x86_64 from @System requires libzypp.so.1735()(64bit), but none of the providers can be installed
  - package zypper-1.14.94-1.fc43.x86_64 from @System requires libzypp.so.1735(ZYPP_plain)(64bit), but none of the providers can be installed
  - package zypper-1.14.94-1.fc43.x86_64 from @System requires libzypp(x86-64) >= 17.37.12, but none of the providers can be installed
  - problem with installed package zypper-log-1.14.94-1.fc43.noarch
  - nothing provides zypp-common = 17.38.1-1.fc43 needed by libzypp-17.38.1-1.fc43.x86_64 from @System

[root@7bd5898f58f4 /]# dnf check --dependencies
libzypp-0:17.38.1-1.fc43.x86_64
 missing require "zypp-common = 17.38.1-1.fc43"
zypp-plugins-0:17.38.1-1.fc43.noarch
 missing require "zypp-common = 17.38.1-1.fc43"
Check discovered 2 problem(s) in 2 package(s)

```
